name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploy dispatch"



#"https://utensils.io/articles/trigger-github-actions-from-another-repo""