name: Android CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Run task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: ./gradlew build
      - name: Dispatch
        run: |
          echo "running tasks"
          sleep 5s

